### ISSUE TITLE
Deploy a pipeline to count the number of citations of a dataset

### ISSUE THREAD

**Issue by ypriverol** [PRIDE-Archive/pride-archive-pipelines#95]
In OmicsdI we deployed a pipeline that computes the number of times a dataset has been cited in publications. This number can be retrieved in two different ways: 

1- By searching the accession in EuroPMC API, this has been already implemented in OmicsDI. We should keep track of those publications in case a user is interested in traceability. 

2- By manual annotation of the reanalysis. In this case, @javizca and @deepte collect a list of papers that reanalyze a dataset and add them to a file in GitHub (for example). WE should then run a pipeline and add those citations.

**Comment by ypriverol** [comment]
@javizca this is the file that you are using for controlling the dataset citations. 

[PRIDE-benchmarking-count_ELIXIR.xlsx](https://github.com/PRIDE-Archive/pride-archive-pipelines/files/4160086/PRIDE-benchmarking-count_ELIXIR.xlsx)

It includes multiple properties such as the title of the paper and type of reanalysis. Can you let me know what information you would like to handle in PRIDE Archive?

**Comment by javizca** [comment]
Yes, this is the December version. I asked Deepti to update it with new entries that were added since, but she have not had the time to do it yet.

**Comment by ypriverol** [comment]
Can you comment, what things you would like to keep from here into the citations count? for traceability

**Comment by javizca** [comment]
I think the paper title including the full reference (and PubMed ID) should be included. I am not so sure about the type of analysis, because it probably lacks consistency overall and some people may complain? The pre-prints probably can be left out for now as well, because that complicates the pipeline, doesn't it? I mean the pre-prints will need to be replaced by the final publication at some point and it is probably easier for the pipeline not to have to handle these cases?

**Comment by ypriverol** [comment]
Then, from this file we really just need: 

`pubmed_id` | `pride_id`

?

**Comment by javizca** [comment]
Other possibility would be just to add the tag "Benchmarking" for those cases where it is mentioned explicitly, and leave empty the other cases. I am pretty sure that in all cases where I wrote "benchmarking", this was really the case. This would be easy to add I think.

For the rest maybe I could review at some point the annotations for the type of reuse to try to be more consistent, and try to add that information later at some point. But that needs some work before it can be added.

**Comment by ypriverol** [comment]
We can have now the following table: 

`pubmed_id` | `pride_id` | `type_citation`

And type citation can use `empty`

**Comment by javizca** [comment]
I think so

**Comment by ypriverol** [comment]
Here the PR https://github.com/PRIDE-Utilities/pride-ontology/pull/15 with the proposal @javizca @deeptijk

**Comment by ypriverol** [comment]
One of the problems of this implementation is that if we get the citations from and the type of the reanalysis from the file if we also implemented the pulling the data from EuroPMC what do we put for those datasets: `NULL`

**Comment by sureshhewabi** [comment]
I have been working on this and I would like to share how data looks like with my current implementation.

There are few types of the records in the CSV: Re-analysis,Re-use, Benchmarking etc.
My Reanalysis pipeline filters out only the records that has "Re-analysis" tag in TypeCitation column to serve data for the following end-point

 **This is what I save in the mongoDB:**

![Screen Shot 2020-05-28 at 9 47 48 AM](https://user-images.githubusercontent.com/5387193/83129551-df6a0680-a0d4-11ea-8e14-0a6794014f55.png)

**This is an example of the reanalysis data I serve from the API end point:**

![Screen Shot 2020-05-28 at 10 16 27 AM](https://user-images.githubusercontent.com/5387193/83129335-90bc6c80-a0d4-11ea-9956-38d829c060b6.png)

I want to know what data exactly we should show in the web and how to present data. Because I might have to modify my API end-point according to the requirement.
